USE universitydb;

SELECT * FROM student;
SELECT * FROM course;
SELECT result FROM score;
SELECT major, syear FROM student;
SELECT cname, st_num FROM course;
SELECT orders FROM professor;
SELECT avr AS '평점' FROM student;
SELECT st_num AS '학점수' FROM course;
SELECT sal * 1.1 AS '10%인상 급여' FROM emp;
SELECT TRUNCATE(avr / 4.0 * 4.5, 2) AS '4.5만점 평점' FROM student;
SELECT sname, avr FROM student ORDER BY avr DESC;
SELECT * FROM student WHERE major = '화학';
SELECT * FROM student WHERE avr < 2.0;
SELECT avr FROM student WHERE sname = '관우';
SELECT * FROM course WHERE pno IS NULL;
SELECT * FROM student WHERE major != '화학' AND syear = 1;
SELECT * FROM student WHERE major = '물리' AND syear = 3;
SELECT * FROM course WHERE pno IS NULL AND st_num = 3;
SELECT * FROM course WHERE cname LIKE '%화학%' AND st_num <= 2;
SELECT * FROM professor WHERE section = '화학' AND orders = '정교수';
SELECT * FROM student WHERE major = '물리' AND sname LIKE '사마%';
SELECT * FROM professor WHERE hiredate < '1995-01-01';
SELECT * FROM professor WHERE CHAR_LENGTH(pname) = 2;
SELECT * FROM student WHERE major IN ('유공','생물','식영') ORDER BY major;
SELECT * FROM student WHERE avr BETWEEN 2.0 AND 3.0;